import './global.css'
import { NextUIProviderWrapper } from './NextUiProviderWrapper'

export const metadata = {
  title: 'Welcome to next-auth',
  description: 'Generated by create-nx-workspace',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <NextUIProviderWrapper>
          <div className="container">
            <main>{children}</main>
          </div>
        </NextUIProviderWrapper>
      </body>
    </html>
  )
}
